### ISSUE TITLE
Have you published the app 

### ISSUE THREAD

**Issue by asselapathirana** [roonie/roku-npo-nederland1#3]
Hi, 

Thanks for this effort. Have you already published the app at the app store as the README.md says. I could not find it searching with terms npo or nederland 1. If it is not published yet, can I use developer mode to install it in my Roku?

**Comment by johanb** [comment]
hey @pcwulf, we've tried to submit them (NL1, NL2, and NL3) to the official channel directory but haven't figured out a proper way for Roku employees to test the channels from their geographic region. As the streams are only available to people inside The Netherlands. 

We had them as private channels before but have since removed those. I will resubmit them as private channels either tonight or tomorrow. That should allow you to add them.

**Comment by asselapathirana** [comment]
hey thanks a lot. In fact i've tested Nederland 1 last night (using your
source) and it works billiently. However, the problem with this approach (I
loading it) is that I can have only one channels installed at a time (there
is a limitation as you know in roku system which allows only one
'development' channel). So, I appreciate your time/effort in resubmitting
them as private channels. Looking forward to install them.

**Comment by johanb** [comment]
We will :) also not all of them are updated to contain the TV Guide yet, will do that to.

**Comment by asselapathirana** [comment]
Hi, where you able to add the channels. If so, what are the codes? I tried to add with (assumed) codes NL1, NL2 and NL3 but did not work..

**Comment by johanb** [comment]
Sorry, didn't get around to it yet. I'll try to do it on saturday. Sorry for the delay.

**Comment by johanb** [comment]
They are all published now:

https://owner.roku.com/add/nederland1
https://owner.roku.com/add/nederland2
https://owner.roku.com/add/nederland3 

Happy watching :)

**Comment by asselapathirana** [comment]
Hi,

Thanks for enabling the channels. However, I still have problems in loading
these as private channels. My roku 3 is a UK model (and registered as UK
not as US). When attempting to register the private channel, my account
complains "We are Sorry. This channels is not available for your area."
 Are your channels registered only for US roku?

Of course my roku is physically in NL and streaming should not be a problem
(for example, when  I side load your nederland1 - it works perfectly). The
problem is registering the private channel at owner.roku.com - it simply
does not allow a UK roku to register them.

**Comment by johanb** [comment]
@pcwulf that's weird, @roonie's Roku is from the UK as well, and it worked for him last night. Which area did you select for your Roku ?

To clarify, it's published in the 'Rest of the World' store. Not in the UK store.

**Comment by roonie** [comment]
I have 2 UK roku LT's, 1 UK roku 2 XS and @gidogeek has a us roku 3, and it works on all of the devises. We submitted the channels for "the rest of the world", so maybe that is the problem your having. Try switching your account to the rest of the world, instead of uk, or usa.

**Comment by asselapathirana** [comment]
Yes. That may be the problem. Is there any possibility that you also submit
it "for uk" (if needed in a different name) and "for us" as well.) This may
have a big influence on how many people in NL use your channels. Here's the
reason: Roku channels for non US/UK people are few and far between.
Therefore many users use some sort of dynamic DNS solution and registration
to use their rokus to 'appear' in UK or US ips. I am sure many viewers in
NL do the same. But the downside of this is that you have to register your
Roku to have a UK or US address and this will make it impossible for them
to register any channels submitted only for "the rest of the world".  This
becomes an issue only when the user is adding the channel, not when
streaming. This is because many DDNS services today are quite smart and
resolve only queries that are needed to access a specific service (e.g. in
the case of UK registration may be BBC iplayer, 5 on demand, Sky,
Netflix-UK etc.) and does not affect the streaming of other channels from
your own country.

I can confirm this at least for my setup: I access almost all services from
UK while in NL and at the same time I can access your NL1 when added as a
'development' channel.

So, if you have a moment to submit it for UK as well - I will try and let
you know if it works. For US testing we have to find someone in NL who is
using a US DNS system - or you can wait until I buy a second Roku which I
will register in US :-) (which I will do pretty soon!).
